EVALUATE
UNION (
    ROW (
        "Table", "DimCustomer",
        "Column", "CustomerKey",
        "Count", COUNT ( 'DimCustomer'[CustomerKey] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[CustomerKey] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[CustomerKey] ),
        "Min", MIN ( 'DimCustomer'[CustomerKey] ),
        "Max", MAX ( 'DimCustomer'[CustomerKey] ),
        "Median", MEDIAN ( 'DimCustomer'[CustomerKey] ),
        "Mean", AVERAGE ( 'DimCustomer'[CustomerKey] ),
        "Standard Deviation", STDEV.P ( 'DimCustomer'[CustomerKey] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', 'DimCustomer'[CustomerKey] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[CustomerKey], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[CustomerKey], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'DimCustomer'[CustomerKey], 0.25 ),
        "P75", PERCENTILE.INC ( 'DimCustomer'[CustomerKey], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "GeographyKey",
        "Count", COUNT ( 'DimCustomer'[GeographyKey] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[GeographyKey] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[GeographyKey] ),
        "Min", MIN ( 'DimCustomer'[GeographyKey] ),
        "Max", MAX ( 'DimCustomer'[GeographyKey] ),
        "Median", MEDIAN ( 'DimCustomer'[GeographyKey] ),
        "Mean", AVERAGE ( 'DimCustomer'[GeographyKey] ),
        "Standard Deviation", STDEV.P ( 'DimCustomer'[GeographyKey] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', 'DimCustomer'[GeographyKey] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[GeographyKey], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[GeographyKey], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'DimCustomer'[GeographyKey], 0.25 ),
        "P75", PERCENTILE.INC ( 'DimCustomer'[GeographyKey], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "CustomerAlternateKey",
        "Count", COUNT ( 'DimCustomer'[CustomerAlternateKey] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[CustomerAlternateKey] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[CustomerAlternateKey] ),
        "Min", MIN ( 'DimCustomer'[CustomerAlternateKey] ),
        "Max", MAX ( 'DimCustomer'[CustomerAlternateKey] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "Title",
        "Count", COUNT ( 'DimCustomer'[Title] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[Title] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[Title] ),
        "Min", MIN ( 'DimCustomer'[Title] ),
        "Max", MAX ( 'DimCustomer'[Title] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "FirstName",
        "Count", COUNT ( 'DimCustomer'[FirstName] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[FirstName] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[FirstName] ),
        "Min", MIN ( 'DimCustomer'[FirstName] ),
        "Max", MAX ( 'DimCustomer'[FirstName] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "MiddleName",
        "Count", COUNT ( 'DimCustomer'[MiddleName] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[MiddleName] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[MiddleName] ),
        "Min", MIN ( 'DimCustomer'[MiddleName] ),
        "Max", MAX ( 'DimCustomer'[MiddleName] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "LastName",
        "Count", COUNT ( 'DimCustomer'[LastName] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[LastName] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[LastName] ),
        "Min", MIN ( 'DimCustomer'[LastName] ),
        "Max", MAX ( 'DimCustomer'[LastName] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "BirthDate",
        "Count", COUNT ( 'DimCustomer'[BirthDate] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[BirthDate] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[BirthDate] ),
        "Min", MIN ( 'DimCustomer'[BirthDate] ),
        "Max", MAX ( 'DimCustomer'[BirthDate] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', 'DimCustomer'[BirthDate] = 0 ) ), 0 ),
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", DATEDIFF ( MIN ( 'DimCustomer'[BirthDate] ), MAX ( 'DimCustomer'[BirthDate] ), DAY ),
        "Range in Months", DATEDIFF ( MIN ( 'DimCustomer'[BirthDate] ), MAX ( 'DimCustomer'[BirthDate] ), MONTH ),
        "Range in Years", DATEDIFF ( MIN ( 'DimCustomer'[BirthDate] ), MAX ( 'DimCustomer'[BirthDate] ), YEAR )
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "MaritalStatus",
        "Count", COUNT ( 'DimCustomer'[MaritalStatus] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[MaritalStatus] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[MaritalStatus] ),
        "Min", MIN ( 'DimCustomer'[MaritalStatus] ),
        "Max", MAX ( 'DimCustomer'[MaritalStatus] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "Suffix",
        "Count", COUNT ( 'DimCustomer'[Suffix] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[Suffix] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[Suffix] ),
        "Min", MIN ( 'DimCustomer'[Suffix] ),
        "Max", MAX ( 'DimCustomer'[Suffix] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "Gender",
        "Count", COUNT ( 'DimCustomer'[Gender] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[Gender] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[Gender] ),
        "Min", MIN ( 'DimCustomer'[Gender] ),
        "Max", MAX ( 'DimCustomer'[Gender] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "EmailAddress",
        "Count", COUNT ( 'DimCustomer'[EmailAddress] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[EmailAddress] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[EmailAddress] ),
        "Min", MIN ( 'DimCustomer'[EmailAddress] ),
        "Max", MAX ( 'DimCustomer'[EmailAddress] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "YearlyIncome",
        "Count", COUNT ( 'DimCustomer'[YearlyIncome] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[YearlyIncome] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[YearlyIncome] ),
        "Min", MIN ( 'DimCustomer'[YearlyIncome] ),
        "Max", MAX ( 'DimCustomer'[YearlyIncome] ),
        "Median", MEDIAN ( 'DimCustomer'[YearlyIncome] ),
        "Mean", AVERAGE ( 'DimCustomer'[YearlyIncome] ),
        "Standard Deviation", STDEV.P ( 'DimCustomer'[YearlyIncome] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', 'DimCustomer'[YearlyIncome] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[YearlyIncome], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[YearlyIncome], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'DimCustomer'[YearlyIncome], 0.25 ),
        "P75", PERCENTILE.INC ( 'DimCustomer'[YearlyIncome], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "TotalChildren",
        "Count", COUNT ( 'DimCustomer'[TotalChildren] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[TotalChildren] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[TotalChildren] ),
        "Min", MIN ( 'DimCustomer'[TotalChildren] ),
        "Max", MAX ( 'DimCustomer'[TotalChildren] ),
        "Median", MEDIAN ( 'DimCustomer'[TotalChildren] ),
        "Mean", AVERAGE ( 'DimCustomer'[TotalChildren] ),
        "Standard Deviation", STDEV.P ( 'DimCustomer'[TotalChildren] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', 'DimCustomer'[TotalChildren] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[TotalChildren], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[TotalChildren], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'DimCustomer'[TotalChildren], 0.25 ),
        "P75", PERCENTILE.INC ( 'DimCustomer'[TotalChildren], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "NumberChildrenAtHome",
        "Count", COUNT ( 'DimCustomer'[NumberChildrenAtHome] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[NumberChildrenAtHome] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[NumberChildrenAtHome] ),
        "Min", MIN ( 'DimCustomer'[NumberChildrenAtHome] ),
        "Max", MAX ( 'DimCustomer'[NumberChildrenAtHome] ),
        "Median", MEDIAN ( 'DimCustomer'[NumberChildrenAtHome] ),
        "Mean", AVERAGE ( 'DimCustomer'[NumberChildrenAtHome] ),
        "Standard Deviation", STDEV.P ( 'DimCustomer'[NumberChildrenAtHome] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', 'DimCustomer'[NumberChildrenAtHome] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[NumberChildrenAtHome], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[NumberChildrenAtHome], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'DimCustomer'[NumberChildrenAtHome], 0.25 ),
        "P75", PERCENTILE.INC ( 'DimCustomer'[NumberChildrenAtHome], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "EnglishEducation",
        "Count", COUNT ( 'DimCustomer'[EnglishEducation] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[EnglishEducation] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[EnglishEducation] ),
        "Min", MIN ( 'DimCustomer'[EnglishEducation] ),
        "Max", MAX ( 'DimCustomer'[EnglishEducation] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "SpanishEducation",
        "Count", COUNT ( 'DimCustomer'[SpanishEducation] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[SpanishEducation] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[SpanishEducation] ),
        "Min", MIN ( 'DimCustomer'[SpanishEducation] ),
        "Max", MAX ( 'DimCustomer'[SpanishEducation] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "FrenchEducation",
        "Count", COUNT ( 'DimCustomer'[FrenchEducation] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[FrenchEducation] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[FrenchEducation] ),
        "Min", MIN ( 'DimCustomer'[FrenchEducation] ),
        "Max", MAX ( 'DimCustomer'[FrenchEducation] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "EnglishOccupation",
        "Count", COUNT ( 'DimCustomer'[EnglishOccupation] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[EnglishOccupation] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[EnglishOccupation] ),
        "Min", MIN ( 'DimCustomer'[EnglishOccupation] ),
        "Max", MAX ( 'DimCustomer'[EnglishOccupation] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "SpanishOccupation",
        "Count", COUNT ( 'DimCustomer'[SpanishOccupation] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[SpanishOccupation] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[SpanishOccupation] ),
        "Min", MIN ( 'DimCustomer'[SpanishOccupation] ),
        "Max", MAX ( 'DimCustomer'[SpanishOccupation] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "FrenchOccupation",
        "Count", COUNT ( 'DimCustomer'[FrenchOccupation] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[FrenchOccupation] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[FrenchOccupation] ),
        "Min", MIN ( 'DimCustomer'[FrenchOccupation] ),
        "Max", MAX ( 'DimCustomer'[FrenchOccupation] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "HouseOwnerFlag",
        "Count", COUNT ( 'DimCustomer'[HouseOwnerFlag] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[HouseOwnerFlag] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[HouseOwnerFlag] ),
        "Min", MIN ( 'DimCustomer'[HouseOwnerFlag] ),
        "Max", MAX ( 'DimCustomer'[HouseOwnerFlag] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "NumberCarsOwned",
        "Count", COUNT ( 'DimCustomer'[NumberCarsOwned] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[NumberCarsOwned] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[NumberCarsOwned] ),
        "Min", MIN ( 'DimCustomer'[NumberCarsOwned] ),
        "Max", MAX ( 'DimCustomer'[NumberCarsOwned] ),
        "Median", MEDIAN ( 'DimCustomer'[NumberCarsOwned] ),
        "Mean", AVERAGE ( 'DimCustomer'[NumberCarsOwned] ),
        "Standard Deviation", STDEV.P ( 'DimCustomer'[NumberCarsOwned] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', 'DimCustomer'[NumberCarsOwned] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[NumberCarsOwned], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[NumberCarsOwned], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'DimCustomer'[NumberCarsOwned], 0.25 ),
        "P75", PERCENTILE.INC ( 'DimCustomer'[NumberCarsOwned], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "AddressLine1",
        "Count", COUNT ( 'DimCustomer'[AddressLine1] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[AddressLine1] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[AddressLine1] ),
        "Min", MIN ( 'DimCustomer'[AddressLine1] ),
        "Max", MAX ( 'DimCustomer'[AddressLine1] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "AddressLine2",
        "Count", COUNT ( 'DimCustomer'[AddressLine2] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[AddressLine2] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[AddressLine2] ),
        "Min", MIN ( 'DimCustomer'[AddressLine2] ),
        "Max", MAX ( 'DimCustomer'[AddressLine2] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "Phone",
        "Count", COUNT ( 'DimCustomer'[Phone] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[Phone] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[Phone] ),
        "Min", MIN ( 'DimCustomer'[Phone] ),
        "Max", MAX ( 'DimCustomer'[Phone] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "DateFirstPurchase",
        "Count", COUNT ( 'DimCustomer'[DateFirstPurchase] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[DateFirstPurchase] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[DateFirstPurchase] ),
        "Min", MIN ( 'DimCustomer'[DateFirstPurchase] ),
        "Max", MAX ( 'DimCustomer'[DateFirstPurchase] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', 'DimCustomer'[DateFirstPurchase] = 0 ) ), 0 ),
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", DATEDIFF ( MIN ( 'DimCustomer'[DateFirstPurchase] ), MAX ( 'DimCustomer'[DateFirstPurchase] ), DAY ),
        "Range in Months", DATEDIFF ( MIN ( 'DimCustomer'[DateFirstPurchase] ), MAX ( 'DimCustomer'[DateFirstPurchase] ), MONTH ),
        "Range in Years", DATEDIFF ( MIN ( 'DimCustomer'[DateFirstPurchase] ), MAX ( 'DimCustomer'[DateFirstPurchase] ), YEAR )
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "CommuteDistance",
        "Count", COUNT ( 'DimCustomer'[CommuteDistance] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[CommuteDistance] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[CommuteDistance] ),
        "Min", MIN ( 'DimCustomer'[CommuteDistance] ),
        "Max", MAX ( 'DimCustomer'[CommuteDistance] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "lastnamelength",
        "Count", COUNT ( 'DimCustomer'[lastnamelength] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[lastnamelength] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[lastnamelength] ),
        "Min", MIN ( 'DimCustomer'[lastnamelength] ),
        "Max", MAX ( 'DimCustomer'[lastnamelength] ),
        "Median", MEDIAN ( 'DimCustomer'[lastnamelength] ),
        "Mean", AVERAGE ( 'DimCustomer'[lastnamelength] ),
        "Standard Deviation", STDEV.P ( 'DimCustomer'[lastnamelength] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', 'DimCustomer'[lastnamelength] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[lastnamelength], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'DimCustomer', MOD ( 'DimCustomer'[lastnamelength], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'DimCustomer'[lastnamelength], 0.25 ),
        "P75", PERCENTILE.INC ( 'DimCustomer'[lastnamelength], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "DimCustomer",
        "Column", "full name",
        "Count", COUNT ( 'DimCustomer'[full name] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'DimCustomer'[full name] ),
        "Null Count", COUNTROWS ( 'DimCustomer' ) - COUNT ( 'DimCustomer'[full name] ),
        "Min", MIN ( 'DimCustomer'[full name] ),
        "Max", MAX ( 'DimCustomer'[full name] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    )
)